/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package operations;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import jxl.Workbook;
import jxl.write.*;

/**
 *
 * @author nihal
 *
 */
public class AprioriTwo extends javax.swing.JFrame {
    
    File file;
    String disp[] = null;
    ArrayList<String> names = new ArrayList<String>();
    ArrayList<Double> values = new ArrayList<Double>();

    /**
     * Creates new form AprioriTwo
     */
    public AprioriTwo() {
        initComponents();
        setVisible(true);
        loadnames();
    }

    void loadnames()
    {
    Connection connection = null;
        ResultSet resultSet = null;
        Statement stmt = null;
        PreparedStatement statement = null;
        try{
             Class.forName("com.mysql.jdbc.Driver");
           connection = DriverManager.getConnection(Constants.DBURL,Constants.USERNAME,Constants.PASSWORD);
DatabaseMetaData dbmd = connection.getMetaData();

    String[] types = { "TABLE" };
    resultSet = dbmd.getTables(null, null, "%", types);
    while (resultSet.next()) {
      String tableName = resultSet.getString(3);
      jComboBox1.addItem(tableName);
      jComboBox2.addItem(tableName);
      
    }


}
catch(ClassNotFoundException | SQLException e){
JOptionPane.showMessageDialog(null, e.getMessage());
}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Select Tables for Apriori Implementation");

        jLabel2.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select Table 1");

        jLabel3.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Select Table 2");

        jButton1.setText("Perform Apriori Algorithm Analyis");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Support (1-100)");

        jButton2.setText("Back to Main Page");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Export");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(491, 491, 491)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel2)
                                .addGap(71, 71, 71)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(jLabel3)
                                .addGap(81, 81, 81)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel4)
                                .addGap(29, 29, 29)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(89, 89, 89))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(219, 219, 219)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        String tablename1="",tablename2="";
        String colnames1[]=null;
        String colnames2[]=null;
        double colvalues1[]=null;
        double colvalues2[]=null;
        String colnames3[]=null;
        double colvalues3[]=null;
        
        
        double total=0;
        DefaultTableModel model=null;
        Connection connection = null;
        Statement stmt = null;
        ResultSet resultSet = null;
        PreparedStatement statement = null;
        String sql="";
        
        int colcount=0;
        double support=0;
        try
        {
            tablename1 = jComboBox1.getSelectedItem().toString();
            tablename2 = jComboBox2.getSelectedItem().toString();
            support = Double.parseDouble(jTextField1.getText());
            Class.forName("com.mysql.jdbc.Driver");
            connection = DriverManager.getConnection(Constants.DBURL,Constants.USERNAME,Constants.PASSWORD);
            sql="select * from "+tablename1;
            statement=connection.prepareStatement(sql);
            resultSet=statement.executeQuery();
            ResultSetMetaData rsmd = resultSet.getMetaData();
            colcount=rsmd.getColumnCount();
            colnames1 = new String[colcount-1];
            colvalues1 = new double[colcount-1];
            resultSet=null;
            for(int i=2;i<=colcount;i++)
            {
                colnames1[i-2] = rsmd.getColumnName(i);
                System.out.println(colnames1[i-2]);
                sql="select SUM("+colnames1[i-2]+") from "+tablename1;
                statement=connection.prepareStatement(sql);
                resultSet=statement.executeQuery();
                if(resultSet.next())
                {
                colvalues1[i-2] = resultSet.getDouble(1);
                System.out.println(colvalues1[i-2]);
                total=total+colvalues1[i-2];
                }
            }
            for(int i=2;i<=colcount;i++)
            {
                colvalues1[i-2] = colvalues1[i-2]/total * 100;
            }
            
            total=0;
            
            //////////////////////////////////////////////////////////////////////////////////////////////////////
            sql="select * from "+tablename2;
            statement=connection.prepareStatement(sql);
            resultSet=statement.executeQuery();
            rsmd = resultSet.getMetaData();
            colcount=rsmd.getColumnCount();
            colnames2 = new String[colcount-1];
            colvalues2 = new double[colcount-1];
            resultSet=null;
            for(int i=2;i<=colcount;i++)
            {
                colnames2[i-2] = rsmd.getColumnName(i);
                System.out.println(colnames2[i-2]);
                sql="select SUM("+colnames2[i-2]+") from "+tablename2;
                statement=connection.prepareStatement(sql);
                resultSet=statement.executeQuery();
                if(resultSet.next())
                {
                colvalues2[i-2] = resultSet.getDouble(1);
                System.out.println(colvalues2[i-2]);
                total=total+colvalues2[i-2];
                }
            }
            for(int i=2;i<=colcount;i++)
            {
                colvalues2[i-2] = colvalues2[i-2]/total * 100;
            }
		
        }
        catch(ClassNotFoundException | NumberFormatException | SQLException e)
        {
            System.out.println(e.getMessage());
        }     
        
        
        for(int i=0;i<colvalues1.length;i++)
        {
        System.out.println(colnames1[i] +"\t"+ colvalues1[i]);
        }
        for(int i=0;i<colvalues2.length;i++)
        {
        System.out.println(colnames2[i] +"\t"+ colvalues2[i]);
        }
        int k=0;
        try
        {
            colnames3 = new String[colnames1.length * colnames2.length];
            disp = new String[colnames1.length * colnames2.length];
            colvalues3 = new double[colnames1.length * colnames2.length];
            for(int i=0;i<colnames1.length;i++)
            {
                for(int j=0;j<colnames2.length;j++)
                {
                    colnames3[k] = colnames1[i] + "  -  "+colnames2[j];
                    colvalues3[k] = (colvalues1[i] + colvalues2[j])/2.0;
                    k++;
                }
            }
            System.out.println("\n");
            for(int i=0;i<colvalues3.length;i++)
            {
                disp[i] = colnames3[i] +"\t"+ colvalues3[i];
                System.out.println(disp[i]);
            }
            
            model = new DefaultTableModel();
            jTable1.setModel(model);
            model.addColumn("Item Sets");
            model.addColumn("Percentile Occurence");
            model.addColumn("Probability");
            int yu = 0;
            for(int i=0;i<colvalues3.length;i++)
            {
                if(colvalues3[i]>=support){
                model.addRow(new Object[]{colnames3[i].substring(0, 15), colvalues3[i],"high"});
                names.add(colnames3[i]);
                values.add(colvalues3[i]);
                yu++;
                }
                else
                {}  
            }
            
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.hide();
        new GenericLoad().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

               String trt = jTextField2.getText().toString();
                //the file path
               file = new File("C:\\Users\\Nihal\\Desktop\\Saved Tables\\"+trt+".xls");
               //if the file not exist create one
               WritableWorkbook myFirstWbook = null;
               if(!file.exists()){
            try {
                file.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(AprioriTwo.class.getName()).log(Level.SEVERE, null, ex);
            }
               }
            try{
                 myFirstWbook = Workbook.createWorkbook(file);
                 WritableSheet excelSheet = myFirstWbook.createSheet("Sheet 1", 0);
                 Label label = new Label(0, 0, "Item Sets");
                 excelSheet.addCell(label);
                 for(int i = 0;i<names.size();i++){
                     excelSheet.addCell(new Label(0,i+1,names.get(i)));
                 }
                 label = new Label(1, 0, "Percentile Occurance");
                 for(int i = 0;i<names.size();i++){
                     excelSheet.addCell(new Label(1,i+1,values.get(i).toString()));
                 }
                 excelSheet.addCell(label);
                 label = new Label(2, 0, "Probability");
                 excelSheet.addCell(label);
                 for(int i = 1;i<names.size();i++){
                     excelSheet.addCell(new Label(2,i+1,"high"));
                 }
                  myFirstWbook.write();
               }   catch (IOException ex) {
                       Logger.getLogger(AprioriTwo.class.getName()).log(Level.SEVERE, null, ex);
                   } catch (WriteException ex) {
                       Logger.getLogger(AprioriTwo.class.getName()).log(Level.SEVERE, null, ex);
                   }finally {

            if (myFirstWbook != null) {
                try {
                    myFirstWbook.close();
                } catch (IOException e) {
                    e.printStackTrace();
                } catch (WriteException e) {
                    e.printStackTrace();
                }
            }
            }
               JOptionPane.showMessageDialog(null, "Data Exported");
               
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
